###  Announce course
POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "code": "course-xxx",
  "name": "Java",
  "limit": 2
}

### Find all courses
GET http://localhost:8080/api/courses

### Enroll in course
POST http://localhost:8080/api/courses/course-xxx/enrollments
Content-Type: application/json

{
  "name": "John {{$random.uuid}}"
}

### Find all enrollments in course
GET http://localhost:8080/api/courses/a/enrollments